changed in scss file for design changing, changed the card background…
nifty-apps/shoppingCart pull request #6
Opened 2023-09-09 17:22 UTC by opu183059

… color on hover and button color is changed a little

2023-09-09 17:23 UTC, opu183059 commented
changed the card hover style

2023-09-11 03:20 UTC, opu183059 commented
Requesting a review from a peer or instructor.

I have changed the card's background color on hover. And also added the git ignore file to ignore the node modules folder. There is no conflict visible in my engine. I requested a PR yesterday but didn't get any response yet. **I am requesting a review from a peer or instructor** again.

2023-09-11 07:47 UTC, Alamgirf12 requested changes
/node_modules

2023-09-11 07:48 UTC, Alamgirf12 approved these changes

2023-09-17 03:15 UTC, merged